name: Build

on:
  release:
    type: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
      - name: Build With Maven
        run: mvn install
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          path: ./target/*.jar